print("Hello Git Lovers!")
name = input("What is your name?")
print("Hello " + name + "!")
movie = input("What is your favorite movie? ")
print(movie + " is a great movie!")
food = input("What would you like to eat today?")
print("Great! I will get you some " + food + "!")
